#!/bin/bash
ansible test -m copy -a "src=/Users/zhujunkai/myhubot/bash/handlers/para dest=/tmp/para owner=root group=root mode=0644"
ansible test -m shell -a "chmod +x /tmp/para"
ansible test -m shell -a "/tmp/para $1"

exit 0